/* Generated By:JavaCC: Do not edit this line. PHPParserConstants.java */
package gatchan.phpparser.parser;

public interface PHPParserConstants {

  int EOF = 0;
  int PHPSTARTSHORT = 1;
  int PHPSTARTLONG = 2;
  int PHPECHOSTART = 3;
  int PHPEND = 4;
  int SINGLE_LINE_COMMENT = 20;
  int PUBLIC = 25;
  int PROTECTED = 26;
  int PRIVATE = 27;
  int ABSTRACT = 28;
  int INTERFACE = 29;
  int IMPLEMENTS = 30;
  int FINAL = 31;
  int CLASS = 32;
  int FUNCTION = 33;
  int VAR = 34;
  int IF = 35;
  int ELSEIF = 36;
  int ELSE = 37;
  int ARRAY = 38;
  int BREAK = 39;
  int LIST = 40;
  int PRINT = 41;
  int ECHO = 42;
  int INCLUDE = 43;
  int REQUIRE = 44;
  int INCLUDE_ONCE = 45;
  int REQUIRE_ONCE = 46;
  int GLOBAL = 47;
  int STATIC = 48;
  int CASE = 49;
  int CONST = 50;
  int CONTINUE = 51;
  int _DEFAULT = 52;
  int DO = 53;
  int EXTENDS = 54;
  int FOR = 55;
  int NEW = 56;
  int RETURN = 57;
  int SWITCH = 58;
  int WHILE = 59;
  int ENDWHILE = 60;
  int ENDSWITCH = 61;
  int ENDIF = 62;
  int ENDFOR = 63;
  int ENDFOREACH = 64;
  int FOREACH = 65;
  int AS = 66;
  int CLASSACCESS = 67;
  int STATICCLASSACCESS = 68;
  int ARRAYASSIGN = 69;
  int DEFINE = 70;
  int GOTO = 71;
  int NULL = 72;
  int SUPER = 73;
  int THIS = 74;
  int TRUE = 75;
  int FALSE = 76;
  int STRING = 77;
  int OBJECT = 78;
  int BOOL = 79;
  int BOOLEAN = 80;
  int REAL = 81;
  int DOUBLE = 82;
  int FLOAT = 83;
  int INT = 84;
  int INTEGER = 85;
  int AT = 86;
  int BANG = 87;
  int TILDE = 88;
  int HOOK = 89;
  int COLON = 90;
  int OR_OR = 91;
  int AND_AND = 92;
  int PLUS_PLUS = 93;
  int MINUS_MINUS = 94;
  int PLUS = 95;
  int MINUS = 96;
  int STAR = 97;
  int SLASH = 98;
  int BIT_AND = 99;
  int BIT_OR = 100;
  int BIT_XOR = 101;
  int REMAINDER = 102;
  int LSHIFT = 103;
  int RSIGNEDSHIFT = 104;
  int RUNSIGNEDSHIFT = 105;
  int _ORL = 106;
  int XOR = 107;
  int _ANDL = 108;
  int INTEGER_LITERAL = 109;
  int DECIMAL_LITERAL = 110;
  int HEX_LITERAL = 111;
  int OCTAL_LITERAL = 112;
  int FLOATING_POINT_LITERAL = 113;
  int EXPONENT = 114;
  int STRING_LITERAL = 115;
  int STRING_1 = 116;
  int STRING_2 = 117;
  int STRING_3 = 118;
  int HEREDOCSTARTTOKEN = 119;
  int DOLLAR = 120;
  int IDENTIFIER = 121;
  int LETTER = 122;
  int DIGIT = 123;
  int SPECIAL = 124;
  int LPAREN = 125;
  int RPAREN = 126;
  int LBRACE = 127;
  int RBRACE = 128;
  int LBRACKET = 129;
  int RBRACKET = 130;
  int SEMICOLON = 131;
  int COMMA = 132;
  int DOT = 133;
  int GT = 134;
  int LT = 135;
  int EQUAL_EQUAL = 136;
  int LE = 137;
  int GE = 138;
  int NOT_EQUAL = 139;
  int DIF = 140;
  int BANGDOUBLEEQUAL = 141;
  int TRIPLEEQUAL = 142;
  int ASSIGN = 143;
  int PLUSASSIGN = 144;
  int MINUSASSIGN = 145;
  int STARASSIGN = 146;
  int SLASHASSIGN = 147;
  int ANDASSIGN = 148;
  int ORASSIGN = 149;
  int XORASSIGN = 150;
  int DOTASSIGN = 151;
  int REMASSIGN = 152;
  int TILDEEQUAL = 153;
  int LSHIFTASSIGN = 154;
  int RSIGNEDSHIFTASSIGN = 155;

  int DEFAULT = 0;
  int PHPPARSING = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int IN_VARIABLE = 3;
  int IN_FORMAL_COMMENT = 4;
  int IN_MULTI_LINE_COMMENT = 5;

  String[] tokenImage = {
    "<EOF>",
    "\"<?\"",
    "\"<?php\"",
    "\"<?=\"",
    "\"?>\"",
    "<token of kind 5>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 18>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 21>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 24>",
    "\"public\"",
    "\"protected\"",
    "\"private\"",
    "\"abstract\"",
    "\"interface\"",
    "\"implements\"",
    "\"final\"",
    "\"class\"",
    "\"function\"",
    "\"var\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"array\"",
    "\"break\"",
    "\"list\"",
    "\"print\"",
    "\"echo\"",
    "\"include\"",
    "\"require\"",
    "\"include_once\"",
    "\"require_once\"",
    "\"global\"",
    "\"static\"",
    "\"case\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"extends\"",
    "\"for\"",
    "\"new\"",
    "\"return\"",
    "\"switch\"",
    "\"while\"",
    "\"endwhile\"",
    "\"endswitch\"",
    "\"endif\"",
    "\"endfor\"",
    "\"endforeach\"",
    "\"foreach\"",
    "\"as\"",
    "\"->\"",
    "\"::\"",
    "\"=>\"",
    "\"define\"",
    "\"goto\"",
    "\"null\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"string\"",
    "\"object\"",
    "\"bool\"",
    "\"boolean\"",
    "\"real\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"integer\"",
    "\"@\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"OR\"",
    "\"XOR\"",
    "\"AND\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<STRING_1>",
    "<STRING_2>",
    "<STRING_3>",
    "\"<<<\"",
    "\"$\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"!==\"",
    "\"===\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\".=\"",
    "\"%=\"",
    "\"~=\"",
    "\"<<=\"",
    "\">>=\"",
  };

}
