/* Generated By:JavaCC: Do not edit this line. PHPParserConstants.java */
package gatchan.phpparser.parser;

public interface PHPParserConstants {

  int EOF = 0;
  int PHPSTARTSHORT = 1;
  int PHPSTARTLONG = 2;
  int PHPECHOSTART = 3;
  int PHPEND = 4;
  int SINGLE_LINE_COMMENT = 20;
  int TODO = 22;
  int CLASS = 26;
  int FUNCTION = 27;
  int VAR = 28;
  int IF = 29;
  int ELSEIF = 30;
  int ELSE = 31;
  int ARRAY = 32;
  int BREAK = 33;
  int LIST = 34;
  int PRINT = 35;
  int ECHO = 36;
  int INCLUDE = 37;
  int REQUIRE = 38;
  int INCLUDE_ONCE = 39;
  int REQUIRE_ONCE = 40;
  int GLOBAL = 41;
  int DEFINE = 42;
  int STATIC = 43;
  int CLASSACCESS = 44;
  int STATICCLASSACCESS = 45;
  int ARRAYASSIGN = 46;
  int CASE = 47;
  int CONST = 48;
  int CONTINUE = 49;
  int _DEFAULT = 50;
  int DO = 51;
  int EXTENDS = 52;
  int FOR = 53;
  int GOTO = 54;
  int NEW = 55;
  int NULL = 56;
  int RETURN = 57;
  int SUPER = 58;
  int SWITCH = 59;
  int THIS = 60;
  int TRUE = 61;
  int FALSE = 62;
  int WHILE = 63;
  int ENDWHILE = 64;
  int ENDSWITCH = 65;
  int ENDIF = 66;
  int ENDFOR = 67;
  int FOREACH = 68;
  int AS = 69;
  int STRING = 70;
  int OBJECT = 71;
  int BOOL = 72;
  int BOOLEAN = 73;
  int REAL = 74;
  int DOUBLE = 75;
  int FLOAT = 76;
  int INT = 77;
  int INTEGER = 78;
  int AT = 79;
  int BANG = 80;
  int TILDE = 81;
  int HOOK = 82;
  int COLON = 83;
  int OR_OR = 84;
  int AND_AND = 85;
  int PLUS_PLUS = 86;
  int MINUS_MINUS = 87;
  int PLUS = 88;
  int MINUS = 89;
  int STAR = 90;
  int SLASH = 91;
  int BIT_AND = 92;
  int BIT_OR = 93;
  int XOR = 94;
  int REMAINDER = 95;
  int LSHIFT = 96;
  int RSIGNEDSHIFT = 97;
  int RUNSIGNEDSHIFT = 98;
  int _ORL = 99;
  int _ANDL = 100;
  int INTEGER_LITERAL = 101;
  int DECIMAL_LITERAL = 102;
  int HEX_LITERAL = 103;
  int OCTAL_LITERAL = 104;
  int FLOATING_POINT_LITERAL = 105;
  int EXPONENT = 106;
  int STRING_LITERAL = 107;
  int STRING_2 = 108;
  int STRING_3 = 109;
  int ESCAPED = 110;
  int DOUBLEQUOTE = 111;
  int DOLLARS = 112;
  int DOUBLEQUOTE2 = 113;
  int LBRACE1 = 114;
  int RBRACE1 = 118;
  int ID = 119;
  int DOLLAR = 122;
  int IDENTIFIER = 123;
  int LETTER = 124;
  int DIGIT = 125;
  int SPECIAL = 126;
  int LPAREN = 128;
  int RPAREN = 129;
  int LBRACE = 130;
  int RBRACE = 131;
  int LBRACKET = 132;
  int RBRACKET = 133;
  int SEMICOLON = 134;
  int COMMA = 135;
  int DOT = 136;
  int GT = 137;
  int LT = 138;
  int EQUAL_EQUAL = 139;
  int LE = 140;
  int GE = 141;
  int NOT_EQUAL = 142;
  int DIF = 143;
  int BANGDOUBLEEQUAL = 144;
  int TRIPLEEQUAL = 145;
  int ASSIGN = 146;
  int PLUSASSIGN = 147;
  int MINUSASSIGN = 148;
  int STARASSIGN = 149;
  int SLASHASSIGN = 150;
  int ANDASSIGN = 151;
  int ORASSIGN = 152;
  int XORASSIGN = 153;
  int DOTASSIGN = 154;
  int REMASSIGN = 155;
  int TILDEEQUAL = 156;
  int LSHIFTASSIGN = 157;
  int RSIGNEDSHIFTASSIGN = 158;

  int DEFAULT = 0;
  int PHPPARSING = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int IN_VARIABLE = 3;
  int IN_FORMAL_COMMENT = 4;
  int IN_MULTI_LINE_COMMENT = 5;
  int IN_STRING = 6;
  int DOLLAR_IN_STRING = 7;
  int SKIPSTRING = 8;
  int DOLLAR_IN_STRING_EXPR = 9;

  String[] tokenImage = {
    "<EOF>",
    "\"<?\"",
    "\"<?php\"",
    "\"<?=\"",
    "\"?>\"",
    "<token of kind 5>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"#\"",
    "<token of kind 18>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 21>",
    "\"todo\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 25>",
    "\"class\"",
    "\"function\"",
    "\"var\"",
    "\"if\"",
    "\"elseif\"",
    "\"else\"",
    "\"array\"",
    "\"break\"",
    "\"list\"",
    "\"print\"",
    "\"echo\"",
    "\"include\"",
    "\"require\"",
    "\"include_once\"",
    "\"require_once\"",
    "\"global\"",
    "\"define\"",
    "\"static\"",
    "\"->\"",
    "\"::\"",
    "\"=>\"",
    "\"case\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"extends\"",
    "\"for\"",
    "\"goto\"",
    "\"new\"",
    "\"null\"",
    "\"return\"",
    "\"super\"",
    "\"switch\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"endwhile\"",
    "\"endswitch\"",
    "\"endif\"",
    "\"endfor\"",
    "\"foreach\"",
    "\"as\"",
    "\"string\"",
    "\"object\"",
    "\"bool\"",
    "\"boolean\"",
    "\"real\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"integer\"",
    "\"@\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"OR\"",
    "\"AND\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<STRING_2>",
    "<STRING_3>",
    "<ESCAPED>",
    "\"\\\"\"",
    "\"$\"",
    "\"\\\"\"",
    "\"{\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 117>",
    "\"}\"",
    "<ID>",
    "<token of kind 120>",
    "<token of kind 121>",
    "\"$\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<SPECIAL>",
    "<token of kind 127>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"<>\"",
    "\"!==\"",
    "\"===\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\".=\"",
    "\"%=\"",
    "\"~=\"",
    "\"<<=\"",
    "\">>=\"",
  };

}
