/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package beauty.parsers.java;

public interface JavaParserConstants {

  int EOF = 0;
  int LINE_ENDERS = 2;
  int BLANK_LINES = 3;
  int SPACES = 4;
  int TABS = 5;
  int END_OF_LINE_COMMENT = 6;
  int JAVADOC_COMMENT = 7;
  int BLOCK_COMMENT = 8;
  int ABSTRACT = 9;
  int ASSERT = 10;
  int BOOLEAN = 11;
  int BREAK = 12;
  int BYTE = 13;
  int CASE = 14;
  int CATCH = 15;
  int CHAR = 16;
  int CLASS = 17;
  int CONST = 18;
  int CONTINUE = 19;
  int _DEFAULT = 20;
  int DO = 21;
  int DOUBLE = 22;
  int ELSE = 23;
  int ENUM = 24;
  int EXTENDS = 25;
  int FALSE = 26;
  int FINAL = 27;
  int FINALLY = 28;
  int FLOAT = 29;
  int FOR = 30;
  int GOTO = 31;
  int IF = 32;
  int IMPLEMENTS = 33;
  int IMPORT = 34;
  int INSTANCEOF = 35;
  int INT = 36;
  int INTERFACE = 37;
  int LONG = 38;
  int NATIVE = 39;
  int NEW = 40;
  int NULL = 41;
  int PACKAGE = 42;
  int PRIVATE = 43;
  int PROTECTED = 44;
  int PUBLIC = 45;
  int RETURN = 46;
  int SHORT = 47;
  int STATIC = 48;
  int STRICTFP = 49;
  int SUPER = 50;
  int SWITCH = 51;
  int SYNCHRONIZED = 52;
  int THIS = 53;
  int THROW = 54;
  int THROWS = 55;
  int TRANSIENT = 56;
  int TRUE = 57;
  int TRY = 58;
  int VOID = 59;
  int VOLATILE = 60;
  int WHILE = 61;
  int INTEGER_LITERAL = 62;
  int DECIMAL_LITERAL = 63;
  int HEX_LITERAL = 64;
  int OCTAL_LITERAL = 65;
  int FLOATING_POINT_LITERAL = 66;
  int EXPONENT = 67;
  int CHARACTER_LITERAL = 68;
  int STRING_LITERAL = 69;
  int IDENTIFIER = 70;
  int LETTER = 71;
  int DIGIT = 72;
  int LPAREN = 73;
  int RPAREN = 74;
  int LBRACE = 75;
  int RBRACE = 76;
  int LBRACKET = 77;
  int RBRACKET = 78;
  int SEMICOLON = 79;
  int COMMA = 80;
  int DOT = 81;
  int AT = 82;
  int ASSIGN = 83;
  int LT = 84;
  int BANG = 85;
  int TILDE = 86;
  int HOOK = 87;
  int COLON = 88;
  int EQ = 89;
  int LE = 90;
  int GE = 91;
  int NE = 92;
  int SC_OR = 93;
  int SC_AND = 94;
  int INCR = 95;
  int DECR = 96;
  int PLUS = 97;
  int MINUS = 98;
  int STAR = 99;
  int SLASH = 100;
  int BIT_AND = 101;
  int BIT_OR = 102;
  int XOR = 103;
  int REM = 104;
  int LSHIFT = 105;
  int PLUSASSIGN = 106;
  int MINUSASSIGN = 107;
  int STARASSIGN = 108;
  int SLASHASSIGN = 109;
  int ANDASSIGN = 110;
  int ORASSIGN = 111;
  int XORASSIGN = 112;
  int REMASSIGN = 113;
  int LSHIFTASSIGN = 114;
  int RSIGNEDSHIFTASSIGN = 115;
  int RUNSIGNEDSHIFTASSIGN = 116;
  int ELLIPSIS = 117;
  int RUNSIGNEDSHIFT = 118;
  int RSIGNEDSHIFT = 119;
  int GT = 120;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\f\"",
    "<LINE_ENDERS>",
    "<BLANK_LINES>",
    "<SPACES>",
    "<TABS>",
    "<END_OF_LINE_COMMENT>",
    "<JAVADOC_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
  };

}
