/* Generated By:JJTree: Do not edit this line. ASTForInStatement.java */

package sidekick.ecmascript.parser;

public class ASTForInStatement extends SimpleNode {
  public ASTForInStatement(int id) {
    super(id);
  }

  public ASTForInStatement(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
