GuiUtils    // 1 passed
GuiUtils.this // 3 passed 
GuiUtils.thing.this // 3 passed
GuiUtils.thing.a.this   // 3 passed
GuiUtils.this.width   // 3 passed
GuiUtils.width.this.length  // 3 passed
GuiUtils.width.this.length.height   // 3 passed
this  // 4 passed
this.width  // 4 passed
this.width.height // 4 passed