/* Generated By:JavaCC: Do not edit this line. HTMLZenParserConstants.java */
/*
 * jEdit - Programmer's Text Editor
 * :tabSize=8:indentSize=8:noTabs=false:
 * :folding=explicit:collapseFolds=1:
 *
 * Copyright © 2011 Matthieu Casanova
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package superabbrevs.zencoding.html;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HTMLZenParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SHARP = 5;
  /** RegularExpression Id. */
  int DOT = 6;
  /** RegularExpression Id. */
  int GT = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int LBRACKET = 10;
  /** RegularExpression Id. */
  int RBRACKET = 11;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int ID_MULTIPLIER = 14;
  /** RegularExpression Id. */
  int MULTIPLIER = 15;
  /** RegularExpression Id. */
  int LITERAL = 16;
  /** RegularExpression Id. */
  int LETTER = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#\"",
    "\".\"",
    "\">\"",
    "\"+\"",
    "\"=\"",
    "\"[\"",
    "\"]\"",
    "<INTEGER_LITERAL>",
    "<IDENTIFIER>",
    "<ID_MULTIPLIER>",
    "<MULTIPLIER>",
    "<LITERAL>",
    "<LETTER>",
    "<DIGIT>",
  };

}
