/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package beauty.parsers.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_ENDERS = 2;
  /** RegularExpression Id. */
  int SPACES = 3;
  /** RegularExpression Id. */
  int TABS = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 5;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int ABSTRACT = 8;
  /** RegularExpression Id. */
  int ASSERT = 9;
  /** RegularExpression Id. */
  int BOOLEAN = 10;
  /** RegularExpression Id. */
  int BREAK = 11;
  /** RegularExpression Id. */
  int BYTE = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int CATCH = 14;
  /** RegularExpression Id. */
  int CHAR = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CONST = 17;
  /** RegularExpression Id. */
  int CONTINUE = 18;
  /** RegularExpression Id. */
  int _DEFAULT = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int DOUBLE = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int ENUM = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINAL = 26;
  /** RegularExpression Id. */
  int FINALLY = 27;
  /** RegularExpression Id. */
  int FLOAT = 28;
  /** RegularExpression Id. */
  int FOR = 29;
  /** RegularExpression Id. */
  int GOTO = 30;
  /** RegularExpression Id. */
  int IF = 31;
  /** RegularExpression Id. */
  int IMPLEMENTS = 32;
  /** RegularExpression Id. */
  int IMPORT = 33;
  /** RegularExpression Id. */
  int INSTANCEOF = 34;
  /** RegularExpression Id. */
  int INT = 35;
  /** RegularExpression Id. */
  int INTERFACE = 36;
  /** RegularExpression Id. */
  int LONG = 37;
  /** RegularExpression Id. */
  int NATIVE = 38;
  /** RegularExpression Id. */
  int NEW = 39;
  /** RegularExpression Id. */
  int NULL = 40;
  /** RegularExpression Id. */
  int PACKAGE = 41;
  /** RegularExpression Id. */
  int PRIVATE = 42;
  /** RegularExpression Id. */
  int PROTECTED = 43;
  /** RegularExpression Id. */
  int PUBLIC = 44;
  /** RegularExpression Id. */
  int RETURN = 45;
  /** RegularExpression Id. */
  int SHORT = 46;
  /** RegularExpression Id. */
  int STATIC = 47;
  /** RegularExpression Id. */
  int STRICTFP = 48;
  /** RegularExpression Id. */
  int SUPER = 49;
  /** RegularExpression Id. */
  int SWITCH = 50;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 51;
  /** RegularExpression Id. */
  int THIS = 52;
  /** RegularExpression Id. */
  int THROW = 53;
  /** RegularExpression Id. */
  int THROWS = 54;
  /** RegularExpression Id. */
  int TRANSIENT = 55;
  /** RegularExpression Id. */
  int TRUE = 56;
  /** RegularExpression Id. */
  int TRY = 57;
  /** RegularExpression Id. */
  int VOID = 58;
  /** RegularExpression Id. */
  int VOLATILE = 59;
  /** RegularExpression Id. */
  int WHILE = 60;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 61;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 62;
  /** RegularExpression Id. */
  int HEX_LITERAL = 63;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 64;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 65;
  /** RegularExpression Id. */
  int EXPONENT = 66;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 67;
  /** RegularExpression Id. */
  int STRING_LITERAL = 68;
  /** RegularExpression Id. */
  int IDENTIFIER = 69;
  /** RegularExpression Id. */
  int LETTER = 70;
  /** RegularExpression Id. */
  int DIGIT = 71;
  /** RegularExpression Id. */
  int LPAREN = 72;
  /** RegularExpression Id. */
  int RPAREN = 73;
  /** RegularExpression Id. */
  int LBRACE = 74;
  /** RegularExpression Id. */
  int RBRACE = 75;
  /** RegularExpression Id. */
  int LBRACKET = 76;
  /** RegularExpression Id. */
  int RBRACKET = 77;
  /** RegularExpression Id. */
  int SEMICOLON = 78;
  /** RegularExpression Id. */
  int COMMA = 79;
  /** RegularExpression Id. */
  int DOT = 80;
  /** RegularExpression Id. */
  int AT = 81;
  /** RegularExpression Id. */
  int ASSIGN = 82;
  /** RegularExpression Id. */
  int LT = 83;
  /** RegularExpression Id. */
  int BANG = 84;
  /** RegularExpression Id. */
  int TILDE = 85;
  /** RegularExpression Id. */
  int HOOK = 86;
  /** RegularExpression Id. */
  int COLON = 87;
  /** RegularExpression Id. */
  int EQ = 88;
  /** RegularExpression Id. */
  int LE = 89;
  /** RegularExpression Id. */
  int GE = 90;
  /** RegularExpression Id. */
  int NE = 91;
  /** RegularExpression Id. */
  int SC_OR = 92;
  /** RegularExpression Id. */
  int SC_AND = 93;
  /** RegularExpression Id. */
  int INCR = 94;
  /** RegularExpression Id. */
  int DECR = 95;
  /** RegularExpression Id. */
  int PLUS = 96;
  /** RegularExpression Id. */
  int MINUS = 97;
  /** RegularExpression Id. */
  int STAR = 98;
  /** RegularExpression Id. */
  int SLASH = 99;
  /** RegularExpression Id. */
  int BIT_AND = 100;
  /** RegularExpression Id. */
  int BIT_OR = 101;
  /** RegularExpression Id. */
  int XOR = 102;
  /** RegularExpression Id. */
  int REM = 103;
  /** RegularExpression Id. */
  int LSHIFT = 104;
  /** RegularExpression Id. */
  int PLUSASSIGN = 105;
  /** RegularExpression Id. */
  int MINUSASSIGN = 106;
  /** RegularExpression Id. */
  int STARASSIGN = 107;
  /** RegularExpression Id. */
  int SLASHASSIGN = 108;
  /** RegularExpression Id. */
  int ANDASSIGN = 109;
  /** RegularExpression Id. */
  int ORASSIGN = 110;
  /** RegularExpression Id. */
  int XORASSIGN = 111;
  /** RegularExpression Id. */
  int REMASSIGN = 112;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 113;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 114;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 115;
  /** RegularExpression Id. */
  int ELLIPSIS = 116;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 117;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 118;
  /** RegularExpression Id. */
  int GT = 119;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\f\"",
    "<LINE_ENDERS>",
    "<SPACES>",
    "<TABS>",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"#\"",
  };

}
