/* Generated By:JavaCC: Do not edit this line. HtmlParserConstants.java */
package sidekick.html.parser.html;

public interface HtmlParserConstants {

  int EOF = 0;
  int ALPHA_CHAR = 1;
  int NUM_CHAR = 2;
  int ALPHANUM_CHAR = 3;
  int IDENTIFIER_CHAR = 4;
  int IDENTIFIER = 5;
  int QUOTED_STRING_NB = 6;
  int QUOTED_STRING = 7;
  int WHITESPACE = 8;
  int NEWLINE = 9;
  int QUOTE = 10;
  int EOL = 11;
  int COMMENT_START = 12;
  int ENDTAG_START = 13;
  int TAG_START = 14;
  int DECL_START = 15;
  int PCDATA = 16;
  int TAG_SCRIPT = 18;
  int TAG_STYLE = 19;
  int TAG_NAME = 20;
  int LST_ERROR = 21;
  int ATTR_NAME = 23;
  int TAG_END = 24;
  int TAG_SLASHEND = 25;
  int ATTR_EQ = 26;
  int IMPLICIT_TAG_END = 27;
  int LIT_ERROR = 28;
  int ATTR_VAL = 30;
  int LAV_ERROR = 31;
  int COMMENT_END = 32;
  int DASH = 33;
  int COMMENT_EOL = 34;
  int COMMENT_WORD = 35;
  int DECL_ANY = 36;
  int DECL_END = 37;
  int SCRIPT_END = 38;
  int STYLE_END = 39;
  int BLOCK_EOL = 40;
  int BLOCK_LBR = 41;
  int BLOCK_WORD = 42;

  int LexStyle = 0;
  int LexScript = 1;
  int LexDecl = 2;
  int LexComment = 3;
  int LexAttrVal = 4;
  int LexInTag = 5;
  int LexStartTag = 6;
  int DEFAULT = 7;

  String[] tokenImage = {
    "<EOF>",
    "<ALPHA_CHAR>",
    "<NUM_CHAR>",
    "<ALPHANUM_CHAR>",
    "<IDENTIFIER_CHAR>",
    "<IDENTIFIER>",
    "<QUOTED_STRING_NB>",
    "<QUOTED_STRING>",
    "<WHITESPACE>",
    "<NEWLINE>",
    "<QUOTE>",
    "<EOL>",
    "<COMMENT_START>",
    "\"</\"",
    "<TAG_START>",
    "\"<!\"",
    "<PCDATA>",
    "<token of kind 17>",
    "\"SCRIPT\"",
    "\"STYLE\"",
    "<TAG_NAME>",
    "<LST_ERROR>",
    "<token of kind 22>",
    "<ATTR_NAME>",
    "<TAG_END>",
    "\"/>\"",
    "\"=\"",
    "\"<\"",
    "<LIT_ERROR>",
    "<token of kind 29>",
    "<ATTR_VAL>",
    "<LAV_ERROR>",
    "<COMMENT_END>",
    "\"-\"",
    "<COMMENT_EOL>",
    "<COMMENT_WORD>",
    "<DECL_ANY>",
    "\">\"",
    "\"</SCRIPT>\"",
    "\"</STYLE>\"",
    "<BLOCK_EOL>",
    "\"<\"",
    "<BLOCK_WORD>",
  };

}
