/*
 * AbbrevsOptionPane.java
 *
 * Created on 27. januar 2007, 22:09
 */

package superabbrevs.gui;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.JPanel;
import org.gjt.sp.jedit.View;
import org.gjt.sp.jedit.jEdit;
import superabbrevs.Abbrev;
import superabbrevs.AbbrevsOptionPaneController;

/**
 *
 * @author  sune
 */
public class AbbrevsOptionPane extends JPanel {
    
    /** 
     * Creates new form AbbrevsOptionPane 
     */
    public AbbrevsOptionPane(View view, AbbrevsOptionPaneController controller) {
        this.mainPanel = this;
        this.controller = controller;
        this.view = view;
        
        abbrevsModel = new AbbrevsListModel(
                controller.loadsAbbrevs(getCurrentMode()));
        initComponents();
        
        // register actions
        ActionMap actionMap = getActionMap();
        actionMap.put(addAction.getValue(Action.NAME), addAction);
        actionMap.put(removeAction.getValue(Action.NAME), removeAction);
        
        // Bind keyboard shortcuts
        InputMap inputMap = getInputMap(WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(
                KeyStroke.getKeyStroke("control N"), 
                addAction.getValue(Action.NAME));
        
        inputMap.put(
                KeyStroke.getKeyStroke("control D"), 
                removeAction.getValue(Action.NAME));
        
        selectFirstAbbrev();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        abbrevsEditorJSplitPane = new javax.swing.JSplitPane();
        abbrevsJPanel = new javax.swing.JPanel();
        modesJComboBox = new javax.swing.JComboBox();
        addJButton = new javax.swing.JButton();
        removeJButton = new javax.swing.JButton();
        modeJLabel = new javax.swing.JLabel();
        abbrevsJLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        abbrevsJList = new javax.swing.JList();
        abbrevsEditorJPanel = new javax.swing.JPanel();
        expansionJLabel = new javax.swing.JLabel();
        abbrevJLabel = new javax.swing.JLabel();
        abbrevJTextField = new javax.swing.JTextField();
        abbrevsEditorJScrollPane = new javax.swing.JScrollPane();
        abbrevsEditorJTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        abbrevsEditorJSplitPane.setDividerLocation(191);
        modesJComboBox.setModel(new DefaultComboBoxModel(controller.getModes()));
        modesJComboBox.setSelectedIndex(controller.getIndexOfCurrentMode());
        modesJComboBox.setNextFocusableComponent(abbrevsJList);
        modesJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modesJComboBoxActionPerformed(evt);
            }
        });

        addJButton.setAction(addAction);
        addJButton.setText("Add...");
        addJButton.getAccessibleContext().setAccessibleName("addJButton");

        removeJButton.setAction(removeAction);
        removeJButton.setText("Remove");
        removeJButton.setEnabled(false);

        modeJLabel.setDisplayedMnemonic('M');
        modeJLabel.setLabelFor(modesJComboBox);
        modeJLabel.setText("Mode:");

        abbrevsJLabel.setDisplayedMnemonic('A');
        abbrevsJLabel.setLabelFor(abbrevsJList);
        abbrevsJLabel.setText("Abbreviations:");

        abbrevsJList.setModel(abbrevsModel);
        abbrevsJList.setNextFocusableComponent(addJButton);
        abbrevsJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                abbrevsJListValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(abbrevsJList);

        javax.swing.GroupLayout abbrevsJPanelLayout = new javax.swing.GroupLayout(abbrevsJPanel);
        abbrevsJPanel.setLayout(abbrevsJPanelLayout);
        abbrevsJPanelLayout.setHorizontalGroup(
            abbrevsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abbrevsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abbrevsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addGroup(abbrevsJPanelLayout.createSequentialGroup()
                        .addComponent(modeJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modesJComboBox, 0, 136, Short.MAX_VALUE))
                    .addComponent(abbrevsJLabel)
                    .addGroup(abbrevsJPanelLayout.createSequentialGroup()
                        .addComponent(addJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeJButton)))
                .addContainerGap())
        );
        abbrevsJPanelLayout.setVerticalGroup(
            abbrevsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abbrevsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abbrevsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeJLabel)
                    .addComponent(modesJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abbrevsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abbrevsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeJButton)
                    .addComponent(addJButton))
                .addContainerGap())
        );
        abbrevsEditorJSplitPane.setLeftComponent(abbrevsJPanel);

        expansionJLabel.setDisplayedMnemonic('E');
        expansionJLabel.setLabelFor(abbrevsEditorJTextArea);
        expansionJLabel.setText("Expansion:");
        expansionJLabel.getAccessibleContext().setAccessibleName("expansionJLabel");

        abbrevJLabel.setDisplayedMnemonic('b');
        abbrevJLabel.setLabelFor(abbrevJTextField);
        abbrevJLabel.setText("Abbreviation:");
        abbrevJLabel.getAccessibleContext().setAccessibleName("abbrevJLabel");

        abbrevJTextField.setEnabled(false);
        abbrevJTextField.setNextFocusableComponent(abbrevsEditorJTextArea);
        abbrevJTextField.getAccessibleContext().setAccessibleName("abbrevJTextField");

        abbrevsEditorJTextArea.setColumns(20);
        abbrevsEditorJTextArea.setRows(5);
        abbrevsEditorJTextArea.setTabSize(4);
        abbrevsEditorJTextArea.setEnabled(false);
        abbrevsEditorJScrollPane.setViewportView(abbrevsEditorJTextArea);

        javax.swing.GroupLayout abbrevsEditorJPanelLayout = new javax.swing.GroupLayout(abbrevsEditorJPanel);
        abbrevsEditorJPanel.setLayout(abbrevsEditorJPanelLayout);
        abbrevsEditorJPanelLayout.setHorizontalGroup(
            abbrevsEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abbrevsEditorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abbrevsEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abbrevsEditorJScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, abbrevsEditorJPanelLayout.createSequentialGroup()
                        .addComponent(abbrevJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abbrevJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                    .addComponent(expansionJLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        abbrevsEditorJPanelLayout.setVerticalGroup(
            abbrevsEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abbrevsEditorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abbrevsEditorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abbrevJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abbrevJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expansionJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abbrevsEditorJScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
        abbrevsEditorJSplitPane.setRightComponent(abbrevsEditorJPanel);

        add(abbrevsEditorJSplitPane, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    private void abbrevsJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_abbrevsJListValueChanged
        int selection = getSelection();
        if(lastSelection != -1 && lastSelection != selection) {
            System.out.println("Save selection "+lastSelection);
            saveAbbrev(lastSelection);
        }
        System.out.println("Selection changed "+getSelection());
        loadAbbrev();
        lastSelection = selection;
    }//GEN-LAST:event_abbrevsJListValueChanged
    
    private void modesJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modesJComboBoxActionPerformed
        // remove the selection
        abbrevsJList.clearSelection();
        abbrevsModel = new AbbrevsListModel(controller.loadsAbbrevs(
                (String)modesJComboBox.getSelectedItem()));
        abbrevsJList.setModel(abbrevsModel);
        selectFirstAbbrev();
    }//GEN-LAST:event_modesJComboBoxActionPerformed
            
    private int getSelection() {
        return abbrevsJList.getSelectedIndex();
    }
    
    private void setSelection(int selection) {
        if(selection != -1) {
            abbrevsJList.setSelectedIndex(selection);
        } else {
            abbrevsJList.clearSelection();
        }
    }
    
    /**
     * Copy all the elements in the abbreviation model to an arraylist and 
     * use the controller to save them.
     */
    public void save() {
        int selection = getSelection();
        if(selection != -1) {
            System.out.println("Save selection "+selection);
            saveAbbrev(selection);
        }
        
        try {
            controller.saveAbbrevs();
        } catch(IOException ex) {
            JOptionPane.showMessageDialog(this, 
                    "Could not write the file abbreviation file", 
                    "Write to file error",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void saveAbbrev(int selection) {
        if(selection  != -1) {
            Abbrev abbrev = abbrevsModel.get(selection);
            
            abbrev.abbrev = abbrevJTextField.getText();
            abbrev.expansion = abbrevsEditorJTextArea.getText();
        }
    }
    
    private void loadAbbrev() {
        int selection = getSelection();
        
        if(selection != -1) {
            Abbrev abbrev = abbrevsModel.get(selection);
            abbrevJTextField.setEnabled(true);
            abbrevJTextField.setText(abbrev.abbrev);
            abbrevsEditorJTextArea.setEnabled(true);
            abbrevsEditorJTextArea.setText(abbrev.expansion);
            removeAction.setEnabled(true);
        } else {
            abbrevJTextField.setText("");
            abbrevsEditorJTextArea.setText("");
            abbrevJTextField.setEnabled(false);
            abbrevsEditorJTextArea.setEnabled(false);
            removeAction.setEnabled(false);
        }
    }

    private String getCurrentMode() {
        String[] modes = controller.getModes();
        return modes[controller.getIndexOfCurrentMode()];
    }

    private void selectFirstAbbrev() {
        if (abbrevsModel.getSize() != 0) {
            abbrevsJList.setSelectedIndex(0);
        } else {
            // If the list is empty clear the selection
            abbrevsJList.clearSelection();
        }
    }
    
    private View view;
    private AbbrevsOptionPaneController controller;
    private AbbrevsListModel abbrevsModel;
    private AbbrevsOptionPane mainPanel;
    private AddAbbrevAction addAction = new AddAbbrevAction(); 
    private RemoveAbbrevAction removeAction = new RemoveAbbrevAction(); 
    private int lastSelection = -1;
    private boolean disabled = false;
    private boolean sorted = true;
    
    private class AddAbbrevAction extends AbstractAction {
        AddAbbrevAction() {
            putValue(Action.NAME, "Add...");
            putValue(Action.LARGE_ICON_KEY, 
                    new javax.swing.ImageIcon(
                    getClass().getResource("/superabbrevs/gui/icons/Plus.png")));
            putValue(Action.MNEMONIC_KEY, KeyEvent.VK_D);
            putValue(Action.DISPLAYED_MNEMONIC_INDEX_KEY, 1);
            putValue(Action.ACCELERATOR_KEY, KeyEvent.VK_D);
            putValue(Action.SHORT_DESCRIPTION, "Add a new abbreviation (Ctrl+N)");
            setEnabled(true);
        }
        
        public void actionPerformed(ActionEvent e) {
            String name = JOptionPane.showInputDialog(mainPanel,
                "Enter the name of the new abbreviation");
            if(name != null) {
                abbrevsJList.clearSelection();
                setSelection(abbrevsModel.add(name));
                abbrevJTextField.grabFocus();
            }
        }
    }
    
    private class RemoveAbbrevAction extends AbstractAction {
        RemoveAbbrevAction() {
            putValue(Action.NAME, "Remove...");
            putValue(Action.LARGE_ICON_KEY, 
                    new javax.swing.ImageIcon(
                    getClass().getResource("/superabbrevs/gui/icons/Minus.png")));
            putValue(Action.MNEMONIC_KEY, KeyEvent.VK_R);
            putValue(Action.DISPLAYED_MNEMONIC_INDEX_KEY, 0);
            putValue(Action.ACCELERATOR_KEY, KeyEvent.VK_R);
            putValue(Action.SHORT_DESCRIPTION, "Remove the selected abbreviation (Ctrl+D)");
            setEnabled(false);
        }
        
        public void actionPerformed(ActionEvent e) {
            int result = JOptionPane.showConfirmDialog(mainPanel,
                "Do you really wish to delete the selected abbreviation",
                    "Delete Abbreviation",JOptionPane.OK_CANCEL_OPTION);
            
            if(result == JOptionPane.OK_OPTION) {
                int selection = getSelection();
                abbrevsJList.clearSelection();
                int newSelection = abbrevsModel.remove(selection);
                
                setSelection(newSelection);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abbrevJLabel;
    private javax.swing.JTextField abbrevJTextField;
    private javax.swing.JPanel abbrevsEditorJPanel;
    private javax.swing.JScrollPane abbrevsEditorJScrollPane;
    private javax.swing.JSplitPane abbrevsEditorJSplitPane;
    private javax.swing.JTextArea abbrevsEditorJTextArea;
    private javax.swing.JLabel abbrevsJLabel;
    private javax.swing.JList abbrevsJList;
    private javax.swing.JPanel abbrevsJPanel;
    private javax.swing.JButton addJButton;
    private javax.swing.JLabel expansionJLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel modeJLabel;
    private javax.swing.JComboBox modesJComboBox;
    private javax.swing.JButton removeJButton;
    // End of variables declaration//GEN-END:variables
}
