/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package beauty.parsers.json;

public interface JsonParserConstants {

  int EOF = 0;
  int LBRACE = 6;
  int RBRACE = 7;
  int LSQUARE = 8;
  int RSQUARE = 9;
  int COMMA = 10;
  int COLON = 11;
  int TRUE = 12;
  int FALSE = 13;
  int NULL = 14;
  int CHAR = 15;
  int STRING = 16;
  int NUMBER = 17;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<CHAR>",
    "<STRING>",
    "<NUMBER>",
  };

}
