/* Generated By:JavaCC: Do not edit this line. FunctionListParserConstants.java */
package gatchan.phpparser.methodlist;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FunctionListParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SLASH = 6;
  /** RegularExpression Id. */
  int PLUS = 7;
  /** RegularExpression Id. */
  int MINUS = 8;
  /** RegularExpression Id. */
  int STAR = 9;
  /** RegularExpression Id. */
  int ASSIGN = 10;
  /** RegularExpression Id. */
  int VARARGSIDENTIFIER = 11;
  /** RegularExpression Id. */
  int VARARGS = 12;
  /** RegularExpression Id. */
  int REF = 13;
  /** RegularExpression Id. */
  int PIPE = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int LBRACKET = 18;
  /** RegularExpression Id. */
  int RBRACKET = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int STRING = 21;
  /** RegularExpression Id. */
  int BOOL = 22;
  /** RegularExpression Id. */
  int INTEGER = 23;
  /** RegularExpression Id. */
  int DOUBLE = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int ARRAY = 26;
  /** RegularExpression Id. */
  int LONG = 27;
  /** RegularExpression Id. */
  int RESOURCE = 28;
  /** RegularExpression Id. */
  int OBJECT = 29;
  /** RegularExpression Id. */
  int MIXED = 30;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 31;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 32;
  /** RegularExpression Id. */
  int FUNCTION_IDENTIFIER = 33;
  /** RegularExpression Id. */
  int IDENTIFIER = 34;
  /** RegularExpression Id. */
  int LETTER = 35;
  /** RegularExpression Id. */
  int DIGIT = 36;
  /** RegularExpression Id. */
  int LITERAL = 37;
  /** RegularExpression Id. */
  int SINGLEQUOTE_LITERAL = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"=\"",
    "\"$...\"",
    "\"...\"",
    "\"&\"",
    "\"|\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"void\"",
    "\"string\"",
    "\"bool\"",
    "\"integer\"",
    "\"double\"",
    "\"int\"",
    "\"array\"",
    "\"long\"",
    "\"resource\"",
    "\"object\"",
    "\"mixed\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<FUNCTION_IDENTIFIER>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<LITERAL>",
    "<SINGLEQUOTE_LITERAL>",
  };

}
