/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gdb_jni_GdbProcess */

#ifndef _Included_gdb_jni_GdbProcess
#define _Included_gdb_jni_GdbProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gdb_jni_GdbProcess
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gdb_jni_GdbProcess_start
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gdb_jni_GdbProcess_end
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    pauseProgram
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gdb_jni_GdbProcess_pauseProgram
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getGdbErrorStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getGdbErrorStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getGdbOutputStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getGdbOutputStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getGdbInputStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getGdbInputStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getProgramErrorStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getProgramErrorStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getProgramOutputStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getProgramOutputStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    getProgramInputStream
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_gdb_jni_GdbProcess_getProgramInputStream
  (JNIEnv *, jobject);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    isReady
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_gdb_jni_GdbProcess_isReady
  (JNIEnv *, jobject, jint);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    readLine
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gdb_jni_GdbProcess_readLine
  (JNIEnv *, jobject, jint);

/*
 * Class:     gdb_jni_GdbProcess
 * Method:    write
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_gdb_jni_GdbProcess_write
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
