/* Generated By:JJTree: Do not edit this line. ASTPropertyValueReference.java */

package sidekick.ecmascript.parser;

public class ASTPropertyValueReference extends SimpleNode {
  public ASTPropertyValueReference(int id) {
    super(id);
  }

  public ASTPropertyValueReference(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
