/* Generated By:JJTree: Do not edit this line. ASTParenExpression.java */

package sidekick.ecmascript.parser;

public class ASTParenExpression extends SimpleNode {
  public ASTParenExpression(int id) {
    super(id);
  }

  public ASTParenExpression(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
