/* Generated By:JavaCC: Do not edit this line. BSHParserConstants.java */
package beauty.parsers.bsh;

public interface BSHParserConstants {

  int EOF = 0;
  int LINE_ENDERS = 2;
  int SPACES = 3;
  int TABS = 4;
  int END_OF_LINE_COMMENT = 5;
  int HASH_BANG_COMMENT = 6;
  int JAVADOC_COMMENT = 7;
  int BLOCK_COMMENT = 8;
  int ABSTRACT = 9;
  int BOOLEAN = 10;
  int BREAK = 11;
  int CLASS = 12;
  int BYTE = 13;
  int CASE = 14;
  int CATCH = 15;
  int CHAR = 16;
  int CONST = 17;
  int CONTINUE = 18;
  int _DEFAULT = 19;
  int DO = 20;
  int DOUBLE = 21;
  int ELSE = 22;
  int ENUM = 23;
  int EXTENDS = 24;
  int FALSE = 25;
  int FINAL = 26;
  int FINALLY = 27;
  int FLOAT = 28;
  int FOR = 29;
  int GOTO = 30;
  int IF = 31;
  int IMPLEMENTS = 32;
  int IMPORT = 33;
  int INSTANCEOF = 34;
  int INT = 35;
  int INTERFACE = 36;
  int LONG = 37;
  int NATIVE = 38;
  int NEW = 39;
  int NULL = 40;
  int PACKAGE = 41;
  int PRIVATE = 42;
  int PROTECTED = 43;
  int PUBLIC = 44;
  int RETURN = 45;
  int SHORT = 46;
  int STATIC = 47;
  int STRICTFP = 48;
  int SWITCH = 49;
  int SYNCHRONIZED = 50;
  int TRANSIENT = 51;
  int THROW = 52;
  int THROWS = 53;
  int TRUE = 54;
  int TRY = 55;
  int VOID = 56;
  int VOLATILE = 57;
  int WHILE = 58;
  int INTEGER_LITERAL = 59;
  int DECIMAL_LITERAL = 60;
  int HEX_LITERAL = 61;
  int OCTAL_LITERAL = 62;
  int FLOATING_POINT_LITERAL = 63;
  int EXPONENT = 64;
  int CHARACTER_LITERAL = 65;
  int STRING_LITERAL = 66;
  int IDENTIFIER = 67;
  int LETTER = 68;
  int DIGIT = 69;
  int LPAREN = 70;
  int RPAREN = 71;
  int LBRACE = 72;
  int RBRACE = 73;
  int LBRACKET = 74;
  int RBRACKET = 75;
  int SEMICOLON = 76;
  int COMMA = 77;
  int DOT = 78;
  int ASSIGN = 79;
  int GT = 80;
  int GTX = 81;
  int LT = 82;
  int LTX = 83;
  int BANG = 84;
  int TILDE = 85;
  int HOOK = 86;
  int COLON = 87;
  int EQ = 88;
  int LE = 89;
  int LEX = 90;
  int GE = 91;
  int GEX = 92;
  int NE = 93;
  int BOOL_OR = 94;
  int BOOL_ORX = 95;
  int BOOL_AND = 96;
  int BOOL_ANDX = 97;
  int INCR = 98;
  int DECR = 99;
  int PLUS = 100;
  int MINUS = 101;
  int STAR = 102;
  int SLASH = 103;
  int BIT_AND = 104;
  int BIT_ANDX = 105;
  int BIT_OR = 106;
  int BIT_ORX = 107;
  int XOR = 108;
  int MOD = 109;
  int LSHIFT = 110;
  int LSHIFTX = 111;
  int RSIGNEDSHIFT = 112;
  int RSIGNEDSHIFTX = 113;
  int RUNSIGNEDSHIFT = 114;
  int RUNSIGNEDSHIFTX = 115;
  int PLUSASSIGN = 116;
  int MINUSASSIGN = 117;
  int STARASSIGN = 118;
  int SLASHASSIGN = 119;
  int ANDASSIGN = 120;
  int ANDASSIGNX = 121;
  int ORASSIGN = 122;
  int ORASSIGNX = 123;
  int XORASSIGN = 124;
  int MODASSIGN = 125;
  int LSHIFTASSIGN = 126;
  int LSHIFTASSIGNX = 127;
  int RSIGNEDSHIFTASSIGN = 128;
  int RSIGNEDSHIFTASSIGNX = 129;
  int RUNSIGNEDSHIFTASSIGN = 130;
  int RUNSIGNEDSHIFTASSIGNX = 131;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"\\f\"",
    "<LINE_ENDERS>",
    "<SPACES>",
    "<TABS>",
    "<END_OF_LINE_COMMENT>",
    "<HASH_BANG_COMMENT>",
    "<JAVADOC_COMMENT>",
    "<BLOCK_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"break\"",
    "\"class\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"transient\"",
    "\"throw\"",
    "\"throws\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"@gt\"",
    "\"<\"",
    "\"@lt\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\"@lteq\"",
    "\">=\"",
    "\"@gteq\"",
    "\"!=\"",
    "\"||\"",
    "\"@or\"",
    "\"&&\"",
    "\"@and\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"@bitwise_and\"",
    "\"|\"",
    "\"@bitwise_or\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"@left_shift\"",
    "\">>\"",
    "\"@right_shift\"",
    "\">>>\"",
    "\"@right_unsigned_shift\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"@and_assign\"",
    "\"|=\"",
    "\"@or_assign\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\"@left_shift_assign\"",
    "\">>=\"",
    "\"@right_shift_assign\"",
    "\">>>=\"",
    "\"@right_unsigned_shift_assign\"",
  };

}
