######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 20 20:10:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
