/*
 * :tabSize=4:indentSize=4:noTabs=true:
 * :folding=explicit:collapseFolds=1:
 *
 * (c) 2005 Marcelo Vanzin
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package p4plugin;

import java.io.BufferedReader;
import java.io.File;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.IOException;
import java.io.OutputStream;
import java.io.StringReader;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;

import org.gjt.sp.jedit.jEdit;
import org.gjt.sp.jedit.View;
import org.gjt.sp.jedit.io.VFSManager;
import org.gjt.sp.util.Log;

import common.threads.WorkerThreadPool;
import common.threads.WorkRequest;

import projectviewer.ProjectViewer;
import projectviewer.PVActions;
import projectviewer.vpt.VPTProject;

import p4plugin.config.P4Config;
import p4plugin.config.P4GlobalConfig;

/**
 *  A wrapper around the perforce executable.
 *
 *  @author     Marcelo Vanzin
 *  @version    $Id$
 *  @since      P4P 0.1
 */
public class Perforce {

    private String          cmd;
    private String[]        args;

    private Process         perforce;
    private StreamReader    stderr;
    private StreamReader    stdout;

    private Visitor         visitor;

    private WorkRequest     stderrReq;
    private WorkRequest     stdoutReq;

    /**
     *  Creates a new wrapper around the p4 command, that will
     *  execute the given command with the given arguments.
     */
    public Perforce(String cmd, String[] args) {
        if (cmd == null)
            throw new IllegalArgumentException("command is null");
        this.cmd    = cmd;
        this.args   = args;
    }

    /**
     *  If the visitor is set to something non-null, instead of
     *  buffering the output of the Perforce command the command
     *  object will call the visitor directly as soon as lines are
     *  read from the output of the process. This makes the process
     *  more memory efficient when processing really long outputs
     *  (like those generated by "p4 files"). Be aware that the
     *  visitor's methods will be called from a thread that might
     *  not be the AWT thread.
     *
     *  @since  P4 0.2.1
     */
    public void setVisitor(Visitor v) {
        this.visitor = v;
    }

    /**
     *  Executes the P4 commmand, returning a process on success.
     *  If an error occurs, a message will be shown to the user
     *  and null will be returned.
     *
     *  <p>The view is also used to get the current active project
     *  and figuring out information about parameters to the p4
     *  executable, such as user, client and editor info.</p>
     *
     *  @since      P4P 0.1
     */
    public Perforce exec(View view) throws IOException {
        if (perforce != null)
            throw new IllegalStateException("can't reuse Perfoce objects");

        int size = 2;
        if (args != null) size += args.length;
        String[] p4cmd = new String[size];

        p4cmd[0] = P4GlobalConfig.getInstance().getPerforcePath();
        if (p4cmd[0] == null)
            throw new IllegalStateException(jEdit.getProperty("p4plugin.no_p4_config"));
        p4cmd[1] = cmd;
        if (args != null) {
            System.arraycopy(args, 0, p4cmd, 2, args.length);
        }

        // print the command to the shell instance
        StringBuilder cmdstr = new StringBuilder("> ");
        for (int i = 0; i < p4cmd.length; i++)
            cmdstr.append(p4cmd[i]).append(" ");
        cmdstr.setLength(cmdstr.length() - 1);
        P4Shell.writeToShell(cmdstr.toString());

        // Try to find the project for the view and see if it has
        // the configuration for perforce.
        String[] envp = null;
        VPTProject proj = ProjectViewer.getActiveProject(view);
        P4Config usercfg = P4Config.getProjectConfig(proj);
        if (usercfg != null) {
            envp = usercfg.getEnv();
        } else {
            view.getStatus().setMessageAndClear(
                jEdit.getProperty("p4plugin.config.no_config_warn"));
        }

        // try to run the command.
        File workdir = null;
        if (proj != null) {
            workdir = new File(proj.getRootPath());
        }
        perforce = Runtime.getRuntime().exec(p4cmd, envp, workdir);

        Runnable stdoutTask;
        stderr = new StreamReader(perforce.getErrorStream(), perforce.getOutputStream(), true);
        stdout = new StreamReader(perforce.getInputStream(), perforce.getOutputStream(), false);

        WorkRequest[] reqs =
            WorkerThreadPool.getSharedInstance().runRequests(
                new Runnable[] { stdout, stderr });
        stdoutReq = reqs[0];
        stderrReq = reqs[1];
        return this;
    }

    public void waitFor() throws InterruptedException {
        perforce.waitFor();
        stdoutReq.waitFor();
        stderrReq.waitFor();
    }

    public String getOutput() {
        if (visitor != null)
            throw new IllegalStateException("no data is buffered if visitor is set");
        if (stdout == null)
            throw new IllegalStateException("command not being executed");
        if (!stdoutReq.isDone())
            throw new IllegalStateException("still reading from process");
        return stdout.getData();
    }

    public String getError() {
        if (stderr == null)
            throw new IllegalStateException("command not being executed");
        if (!stderrReq.isDone())
            throw new IllegalStateException("still reading from process");
        return stderr.getData();
    }

    public Process getProcess() {
        return perforce;
    }

    public boolean isSuccess() {
        return (perforce.exitValue() == 0);
    }

    public void showError(View v) {
        String msg = "Exit status: " + perforce.exitValue() + "\n\n" + getError();
        showDialog(v, msg);
        Log.log(Log.ERROR, this, getError());
    }

    private void showDialog(final View v, String msg) {
        final JTextArea message = new JTextArea(24, 80);
        message.setText(msg);
        PVActions.swingInvoke(
            new Runnable() {
                public void run() {
                    JOptionPane.showMessageDialog(v,
                        new JScrollPane(message),
                        jEdit.getProperty("p4plugin.p4_error.title"),
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        );
    }

    public void processOutput(Visitor visitor) {
        // break the list into individual lines.
        try {
            BufferedReader br = new BufferedReader(new StringReader(getOutput()));
            String line;
            while ((line = br.readLine()) != null)
                if (!visitor.process(line))
                    break;
            br.close();
        } catch (IOException ioe) {
            // not gonna happen for StringReader.
        }
    }

    private class StreamReader implements Runnable {

        private boolean         foundError;
        private boolean         iserr;
        private InputStream     input;
        private OutputStream    output;

        private StringBuilder    data;

        public StreamReader(InputStream in, OutputStream out, boolean iserr) {
            this.input  = in;
            this.output = out;
            this.iserr  = iserr;

            this.data       = new StringBuilder();
            this.foundError = false;
        }

        public void run() {
            try {
                byte[] buf = new byte[128];
                while (true) {
                    int read = input.read(buf);
                    if (read == -1)
                       break;

                    for (int i = 0; i < read; i++)
                        data.append((char)buf[i]);

                    if (visitor != null) {
                        int idx;
                        while ( (idx = data.indexOf("\n")) >= 0) {
                            if (idx > 0 && data.charAt(idx - 1) == '\r') {
                                // ah, windows.
                                idx--;
                            }
                            String line = data.substring(0, idx);
                            data.delete(0, idx + 1);
                            if (!foundError) {
                                foundError = checkErrorMessage(line);
                                if (!foundError && !iserr) {
                                    visitor.process(line);
                                }
                            } else if (!iserr) {
                                visitor.process(line);
                            }
                            if (foundError) {
                                break;
                            }
                        }
                    }

                    if (!foundError) {
                        foundError = checkErrorMessage(data.toString());
                    }
                }
            } catch (IOException ioe) {
                Log.log(Log.DEBUG, this, ioe);
            }
        }

        public String getData() {
            return data.toString();
        }

        private boolean checkErrorMessage(String str)
            throws IOException
        {
            if (str.indexOf("Hit return to continue") >= 0) {
                PVActions.swingInvoke(
                    new Runnable() {
                        public void run() {
                            showDialog(jEdit.getActiveView(),
                                       jEdit.getProperty("p4plugin.retry_msg"));
                        }
                    }
                );
                output.write("\n".getBytes());
                output.flush();
                return true;
            } else if (str.indexOf("Perforce client error:") >= 0) {
                return true;
            }
            return false;
        }
    }

    /**
     *  Interface to implement a "visitor" pattern and make it easier to
     *  process the output of the command (less "cookie cutter" code).
     */
    public static interface Visitor {

        /**
         *  Called once for every line in the output.
         *
         *  @return Whether to continue reading the output.
         */
        public boolean process(String line);

    }

}

