/* Generated By:JJTree: Do not edit this line. ASTArrayLiteral.java */

package sidekick.ecmascript.parser;

public class ASTArrayLiteral extends SimpleNode {
  public ASTArrayLiteral(int id) {
    super(id);
  }

  public ASTArrayLiteral(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
