/* Generated By:JJTree: Do not edit this line. ASTFunctionCallParameters.java */

package sidekick.ecmascript.parser;

public class ASTFunctionCallParameters extends SimpleNode {
  public ASTFunctionCallParameters(int id) {
    super(id);
  }

  public ASTFunctionCallParameters(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

}
