/* Generated By:JJTree: Do not edit this line. ASTObjectLiteral.java */

package sidekick.ecmascript.parser;

public class ASTObjectLiteral extends SimpleNode {
  public ASTObjectLiteral(int id) {
    super(id);
  }

  public ASTObjectLiteral(EcmaScript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(EcmaScriptVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
